//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Order_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Total_Amount { get; set; }
        public Nullable<int> Discount_Id { get; set; }
        public string Ship_Address { get; set; }
        public string Ship_Email { get; set; }
        public string Ship_PhoneNumber { get; set; }
        public string Ship_Note { get; set; }
        public Nullable<int> Status { get; set; }
        public string Ship_Name { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
