//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebBanGiayEntities : DbContext
    {
        public WebBanGiayEntities()
            : base("name=WebBanGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WareHouse> WareHouses { get; set; }
    
        public virtual int SP_NhapHang(Nullable<int> iDSanPham, Nullable<double> kichThuoc, Nullable<int> soLuongNhap)
        {
            var iDSanPhamParameter = iDSanPham.HasValue ?
                new ObjectParameter("IDSanPham", iDSanPham) :
                new ObjectParameter("IDSanPham", typeof(int));
    
            var kichThuocParameter = kichThuoc.HasValue ?
                new ObjectParameter("KichThuoc", kichThuoc) :
                new ObjectParameter("KichThuoc", typeof(double));
    
            var soLuongNhapParameter = soLuongNhap.HasValue ?
                new ObjectParameter("SoLuongNhap", soLuongNhap) :
                new ObjectParameter("SoLuongNhap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NhapHang", iDSanPhamParameter, kichThuocParameter, soLuongNhapParameter);
        }
    
        public virtual ObjectResult<SP_XemKhoHangTuSanPham_Result> SP_XemKhoHangTuSanPham(Nullable<int> iDSanPham)
        {
            var iDSanPhamParameter = iDSanPham.HasValue ?
                new ObjectParameter("IDSanPham", iDSanPham) :
                new ObjectParameter("IDSanPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemKhoHangTuSanPham_Result>("SP_XemKhoHangTuSanPham", iDSanPhamParameter);
        }
    
        public virtual ObjectResult<spDanhSachSanPham_Result> spDanhSachSanPham(string filter, Nullable<int> idCategory, Nullable<int> idBrand)
        {
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var idCategoryParameter = idCategory.HasValue ?
                new ObjectParameter("idCategory", idCategory) :
                new ObjectParameter("idCategory", typeof(int));
    
            var idBrandParameter = idBrand.HasValue ?
                new ObjectParameter("idBrand", idBrand) :
                new ObjectParameter("idBrand", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDanhSachSanPham_Result>("spDanhSachSanPham", filterParameter, idCategoryParameter, idBrandParameter);
        }
    
        public virtual int spXoaSanPhamTrongKhoHang(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaSanPhamTrongKhoHang", product_idParameter);
        }
    }
}
